name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v4  
    - name: Set up Docker  
      uses: docker/setup-buildx-action@v2  
    - name: Build and run Docker Compose  
      uses: core/docker-compose@v2  
      with:  
        compose-file: docker-compose.yml  
        run: true  
    - name: Run Test  
      run: docker exec backend sh -c "pytest ."  

