name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker-compose
      run: docker-compose up -d
    - name: Wait for backend to be ready  
      run: |  
        for i in {1..30}; do  
            if [ "$(docker inspect -f '{{.State.Running}}' backend)" == "true" ]; then  
              break  
            fi  
            sleep 1  
        done  
    - name: Run Test
      run: docker exec backend sh -c "pytest ."
