name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
   
    steps:  
    - uses: actions/checkout@v4  
    
    - name: Install Docker  
      run: |  
        sudo apt-get remove docker docker-engine docker.io containerd runc -y || true  
        sudo apt-get update  
        sudo apt-get install ca-certificates curl gnupg lsb-release -y  
        sudo mkdir -p /etc/apt/keyrings  
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null  
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.gpg >/dev/null  
        sudo apt-get update  
        sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y  
        
    - name: Run Docker Compose  
      run: docker-compose up -d  
      
    - name: Run Tests  
      run: docker exec backend sh -c "pytest ."  
