name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:  
        - name: Checkout repository  
          uses: actions/checkout@v2  
    
        - name: Run Docker Compose  
          run: |  
            sudo docker-compose up -d  
          
        - name: test Docker
          run : docker exec backend sh -c "flake8 && pytest . "
    


