name: Test1

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Test:
    name: Test

    runs-on: ubuntu-latest
    
    steps:  
        - name: Checkout repository  
          uses: actions/checkout@v2  
          
        - name: Install Docker Compose  
          run: |  
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose  
            sudo chmod +x /usr/local/bin/docker-compose  
    
        - name: Run Docker Compose  
          run: |  
            sudo docker-compose up -d  
          
        - name: test Docker
          run : docker exec backend sh -c "flake8 && pytest . "

  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v3
    - name: Checkout repository  
      uses: appleboy/ssh-action@v3
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        script: ls

        


